(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const norm=s=>String(s||'').toLocaleLowerCase('de').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');
  let seed=[],extra=[],cover=null,loading=false;
  function all(){const bySku=new Map(seed.map(s=>[s.sku,s]));for(const s of extra)bySku.set(s.sku,s);return [...bySku.values()].sort((a,b)=>a.name.localeCompare(b.name,'de'));}
  function elt(tag,cls,content){const node=document.createElement(tag);if(cls)node.className=cls;if(content!==undefined)node.textContent=content;return node;}
  function showMessage(message,isError=false,inside=false){const target=inside?$('formMessage'):$('feedback');target.hidden=false;target.className='notice '+(isError?'danger':'success');target.replaceChildren(elt('span','',message));}
  function draw(){const terms=norm($('q').value).trim().split(/\s+/).filter(Boolean);const records=all();const visible=records.filter(s=>terms.every(t=>norm([s.name,s.sku,s.motifs,s.topics,...(s.phrases||[])].join(' ')).includes(t)));
    $('cards').replaceChildren();for(const s of visible){const card=elt('article','card');const coverDiv=elt('div','cover');if(s.imageKey){const img=document.createElement('img');img.loading='lazy';img.src=s.imageKey;img.alt='Cover: '+s.name;coverDiv.append(img);}else coverDiv.append(elt('div','placeholder',s.name));card.append(coverDiv);
      const body=elt('div','cardbody');body.append(elt('span','sku','ART.-NR. '+s.sku),elt('h3','',s.name));if(s.motifs)body.append(elt('p','motifs',s.motifs));const phrases=elt('div','phrases');for(const text of (s.phrases||[]).slice(0,3))phrases.append(elt('span','','„'+text+'“'));if((s.phrases||[]).length>3)phrases.append(elt('small','',`+${s.phrases.length-3} weitere`));body.append(phrases);if(s.topics){const tags=elt('p','topics');for(const t of s.topics.split(',').slice(0,3))tags.append(elt('span','',t.trim()));body.append(tags);}if(s.location)body.append(elt('p','location','Aufbewahrung: '+s.location));card.append(body);$('cards').append(card);}
    $('count').textContent=visible.length+' von '+records.length+' Stempelsets';$('empty').hidden=visible.length!==0;$('heading').textContent=terms.length?'Suchergebnisse':'Alle Stempelsets';$('clear').hidden=!$('q').value;}
  async function refresh(){try{const [staticResponse,dynamicResponse]=await Promise.all([fetch('/seed.json',{cache:'no-store'}),fetch('/.netlify/functions/sets',{cache:'no-store'})]);if(!staticResponse.ok)throw Error('Der Startbestand konnte nicht geladen werden.');seed=await staticResponse.json();if(!dynamicResponse.ok)throw Error('Der gemeinsame Bestand ist noch nicht erreichbar.');extra=await dynamicResponse.json();$('feedback').hidden=true;}catch(e){if(!seed.length){try{seed=await (await fetch('/seed.json',{cache:'no-store'})).json();}catch{}}showMessage(e.message||'Der Bestand konnte nicht geladen werden.',true);}finally{draw();}}
  async function compressImage(file){if(file.size<=1_800_000&&['image/jpeg','image/png','image/webp'].includes(file.type))return file;const bitmap=await createImageBitmap(file);try{const ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.77));if(!blob||blob.size>2_000_000)throw Error('Das Bild konnte nicht unter 2 MB verkleinert werden.');return new File([blob],'cover.jpg',{type:'image/jpeg'});}finally{bitmap.close();}}
  function readCover(file){const url=URL.createObjectURL(file);const img=$('preview');if(img.dataset.objectUrl)URL.revokeObjectURL(img.dataset.objectUrl);img.src=url;img.dataset.objectUrl=url;img.hidden=false;$('cameraPrompt').hidden=true;$('scanStatus').textContent='Foto wird gelesen …';
    if(!window.Tesseract){$('scanStatus').textContent='Foto ausgewählt. Bitte Angaben selbst eintragen.';return;}
    window.Tesseract.createWorker('deu+eng').then(async worker=>{try{const result=await worker.recognize(file);const text=result.data.text;const number=text.match(/\b1[0-9]{5}\b/)?.[0];if(number)$('sku').value=number;const title=text.split('\n').map(s=>s.trim()).find(line=>/^[A-ZÄÖÜ][A-ZÄÖÜ\s'-]{5,}$/.test(line)&&!/STEMPEL|STAMP|KLARSICHT/.test(line));if(title)$('name').value=title.toLocaleLowerCase('de').replace(/(^|\s)\S/g,c=>c.toLocaleUpperCase('de'));$('scanStatus').textContent='Foto gelesen. Bitte alle erkannten Angaben prüfen.';}finally{await worker.terminate();}}).catch(()=>$('scanStatus').textContent='Foto ausgewählt. Bitte Angaben selbst eintragen.');}
  async function lookup(){const sku=$('sku').value.trim();if(!/^\d{5,9}$/.test(sku)){showMessage('Bitte eine gültige Artikelnummer eingeben.',true,true);return;}const known=all().find(s=>s.sku===sku);if(known){$('name').value=known.name;$('formMessage').hidden=false;showMessage('Dieses Set ist bereits im gemeinsamen Bestand: '+known.name,true,true);return;}
    $('lookup').disabled=true;try{const response=await fetch('/.netlify/functions/lookup?sku='+encodeURIComponent(sku),{cache:'no-store'});const data=await response.json();if(response.ok&&data.name){$('name').value=data.name;showMessage('Produktname beim Hersteller gefunden. Bitte Angaben und Cover prüfen.',false,true);}else{showMessage(data.error||'Beim Hersteller nicht gefunden. Erfasse das Set mit einem eigenen Foto.',true,true);if(data.searchUrl){const a=elt('a','','Artikelnummer zusätzlich im Web suchen ↗');a.href=data.searchUrl;a.target='_blank';a.rel='noopener noreferrer';$('formMessage').append(' ',a);}}}catch{showMessage('Die Suche ist nicht verfügbar. Bitte Daten selbst eintragen.',true,true);}finally{$('lookup').disabled=false;}}
  async function save(event){event.preventDefault();if(loading)return;const form=$('form');if(!form.reportValidity())return;loading=true;$('save').disabled=true;$('save').textContent='Speichern …';$('formMessage').hidden=true;try{const selected=$('photo').files?.[0];if(selected)cover=await compressImage(selected);const data=new FormData(form);data.delete('password');data.delete('photo');if(cover)data.set('image',cover);const password=$('password').value;const response=await fetch('/.netlify/functions/sets',{method:'POST',headers:{'X-Admin-Password':password},body:data,cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error||'Speichern fehlgeschlagen.');$('editor').close();form.reset();$('preview').hidden=true;$('cameraPrompt').hidden=false;$('scanStatus').textContent='';cover=null;$('password').value='';await refresh();showMessage('„'+result.name+'“ wurde gespeichert und ist jetzt für alle sichtbar.');}catch(e){showMessage(e.message||'Speichern fehlgeschlagen.',true,true);}finally{loading=false;$('save').disabled=false;$('save').textContent='Für alle speichern';}}
  $('q').addEventListener('input',draw);$('clear').addEventListener('click',()=>{$('q').value='';draw();$('q').focus();});$('add').addEventListener('click',()=>{$('formMessage').hidden=true;$('editor').showModal();});$('close').addEventListener('click',()=>$('editor').close());$('cancel').addEventListener('click',()=>$('editor').close());$('editor').addEventListener('click',event=>{if(event.target===$('editor'))$('editor').close();});$('lookup').addEventListener('click',lookup);$('photo').addEventListener('change',event=>{const file=event.target.files?.[0];if(file)readCover(file);});$('form').addEventListener('submit',save);
  refresh();setInterval(refresh,30000);
})();
