(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const norm=s=>String(s||'').toLocaleLowerCase('de').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss');
  let seed=[],extra=[],cover=null,loading=false,editingSku=null;
  const phraseScroll=new Map();
  function all(){const bySku=new Map(seed.map(s=>[s.sku,s]));for(const s of extra){if(s.deleted)bySku.delete(s.sku);else bySku.set(s.sku,s);}return [...bySku.values()].sort((a,b)=>a.name.localeCompare(b.name,'de'));}
  function elt(tag,cls,content){const node=document.createElement(tag);if(cls)node.className=cls;if(content!==undefined)node.textContent=content;return node;}
  function showMessage(message,isError=false,inside=false){const target=inside?$('formMessage'):$('feedback');target.hidden=false;target.className='notice '+(isError?'danger':'success');target.replaceChildren(elt('span','',message));}
  function draw(){const terms=norm($('q').value).trim().split(/\s+/).filter(Boolean);const records=all();const visible=records.filter(s=>terms.every(t=>norm([s.name,s.sku,s.motifs,s.topics,...(s.phrases||[])].join(' ')).includes(t)));
    $('cards').replaceChildren();for(const s of visible){const card=elt('article','card');const coverDiv=elt('div','cover');if(s.imageKey){const open=elt('button','cover-open');open.type='button';open.setAttribute('aria-label','Cover von '+s.name+' groß anzeigen');const img=document.createElement('img');img.loading='lazy';img.src=s.imageKey;img.alt='Cover: '+s.name;open.append(img);open.addEventListener('click',()=>{$('largeImage').src=img.src;$('largeImage').alt=img.alt;$('largeCaption').textContent=s.name;$('imageDialog').showModal();});coverDiv.append(open);const covers=[s.imageKey,...(s.additionalImages||[])];if(covers.length>1){let current=0;const next=elt('button','more-covers',`Bild 1/${covers.length} · Weiter ›`);next.type='button';next.setAttribute('aria-label','Nächstes Cover von '+s.name);next.addEventListener('click',()=>{current=(current+1)%covers.length;img.src=covers[current];next.textContent=`Bild ${current+1}/${covers.length} · Weiter ›`;});coverDiv.append(next);}}else coverDiv.append(elt('div','placeholder',s.name));card.append(coverDiv);
      const body=elt('div','cardbody');body.append(elt('span','sku','ART.-NR. '+s.sku),elt('h3','',s.name));if(s.motifs)body.append(elt('p','motifs',s.motifs));const phrases=elt('div','phrases');if((s.phrases||[]).length){phrases.setAttribute('aria-label','Alle Sprüche von '+s.name);phrases.tabIndex=0;for(const sentence of s.phrases)phrases.append(elt('span','',`„${sentence}“`));phrases.scrollTop=phraseScroll.get(s.sku)||0;phrases.addEventListener('scroll',()=>phraseScroll.set(s.sku,phrases.scrollTop));}body.append(phrases);if(s.topics){const tags=elt('p','topics');for(const t of s.topics.split(',').slice(0,3))tags.append(elt('span','',t.trim()));body.append(tags);}if(s.location)body.append(elt('p','location','Aufbewahrung: '+s.location));{const actions=elt('div','card-actions');const edit=elt('button','secondary','Bearbeiten');edit.type='button';edit.addEventListener('click',()=>openEditor(s));const del=elt('button','secondary','Löschen');del.type='button';del.addEventListener('click',()=>deleteSet(s));actions.append(edit,del);body.append(actions);}card.append(body);$('cards').append(card);}
    $('count').textContent=visible.length+' von '+records.length+' Stempelsets';$('empty').hidden=visible.length!==0;$('heading').textContent=terms.length?'Suchergebnisse':'Alle Stempelsets';$('clear').hidden=!$('q').value;}
  async function refresh(){try{const [staticResponse,dynamicResponse]=await Promise.all([fetch('/seed.json',{cache:'no-store'}),fetch('/.netlify/functions/sets',{cache:'no-store'})]);if(!staticResponse.ok)throw Error('Der Startbestand konnte nicht geladen werden.');seed=await staticResponse.json();if(!dynamicResponse.ok)throw Error('Der gemeinsame Bestand ist noch nicht erreichbar.');extra=await dynamicResponse.json();$('feedback').hidden=true;}catch(e){if(!seed.length){try{seed=await (await fetch('/seed.json',{cache:'no-store'})).json();}catch{}}showMessage(e.message||'Der Bestand konnte nicht geladen werden.',true);}finally{draw();}}
  async function compressImage(file){if(file.size<=1_800_000&&['image/jpeg','image/png','image/webp'].includes(file.type))return file;const bitmap=await createImageBitmap(file);try{const ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.77));if(!blob||blob.size>2_000_000)throw Error('Das Bild konnte nicht unter 2 MB verkleinert werden.');return new File([blob],'cover.jpg',{type:'image/jpeg'});}finally{bitmap.close();}}
  function readCover(file){cover=null;const url=URL.createObjectURL(file);const img=$('preview');if(img.dataset.objectUrl)URL.revokeObjectURL(img.dataset.objectUrl);img.src=url;img.dataset.objectUrl=url;img.hidden=false;$('cameraPrompt').hidden=true;$('cropOpen').hidden=false;$('removeCover').checked=false;$('scanStatus').textContent='Foto wird gelesen …';
    if(!window.Tesseract){$('scanStatus').textContent='Foto ausgewählt. Bitte Angaben selbst eintragen.';return;}
    window.Tesseract.createWorker('deu+eng').then(async worker=>{try{const result=await worker.recognize(file);const text=result.data.text;const number=text.match(/\b1[0-9]{5}\b/)?.[0];if(number)$('sku').value=number;const title=text.split('\n').map(s=>s.trim()).find(line=>/^[A-ZÄÖÜ][A-ZÄÖÜ\s'-]{5,}$/.test(line)&&!/STEMPEL|STAMP|KLARSICHT/.test(line));if(title)$('name').value=title.toLocaleLowerCase('de').replace(/(^|\s)\S/g,c=>c.toLocaleUpperCase('de'));$('scanStatus').textContent='Foto gelesen. Bitte alle erkannten Angaben prüfen.';}finally{await worker.terminate();}}).catch(()=>$('scanStatus').textContent='Foto ausgewählt. Bitte Angaben selbst eintragen.');}
  async function lookup(){const sku=$('sku').value.trim();if(!/^\d{5,9}$/.test(sku)){showMessage('Bitte eine gültige Artikelnummer eingeben.',true,true);return;}const known=all().find(s=>s.sku===sku);if(known){$('name').value=known.name;$('formMessage').hidden=false;showMessage('Dieses Set ist bereits im gemeinsamen Bestand: '+known.name,true,true);return;}
    $('lookup').disabled=true;try{const response=await fetch('/.netlify/functions/lookup?sku='+encodeURIComponent(sku),{cache:'no-store'});const data=await response.json();if(response.ok&&data.name){$('name').value=data.name;showMessage('Produktname beim Hersteller gefunden. Bitte Angaben und Cover prüfen.',false,true);}else{showMessage(data.error||'Beim Hersteller nicht gefunden. Erfasse das Set mit einem eigenen Foto.',true,true);if(data.searchUrl){const a=elt('a','','Artikelnummer zusätzlich im Web suchen ↗');a.href=data.searchUrl;a.target='_blank';a.rel='noopener noreferrer';$('formMessage').append(' ',a);}}}catch{showMessage('Die Suche ist nicht verfügbar. Bitte Daten selbst eintragen.',true,true);}finally{$('lookup').disabled=false;}}
  function clearPreview(){const img=$('preview');if(img.dataset.objectUrl)URL.revokeObjectURL(img.dataset.objectUrl);delete img.dataset.objectUrl;img.removeAttribute('src');img.hidden=true;$('cameraPrompt').hidden=false;$('cropOpen').hidden=true;}
  let cropBitmap=null,cropRect=null,cropStart=null;
  function cropDraw(){if(!cropBitmap)return;const canvas=$('cropCanvas'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(cropBitmap,0,0,canvas.width,canvas.height);if(cropRect){const {x,y,w,h}=cropRect;ctx.fillStyle='rgba(20,35,25,.55)';ctx.fillRect(0,0,canvas.width,y);ctx.fillRect(0,y,x,h);ctx.fillRect(x+w,y,canvas.width-x-w,h);ctx.fillRect(0,y+h,canvas.width,canvas.height-y-h);ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(2,canvas.width/400);ctx.strokeRect(x,y,w,h);}}
  function cropSize(){const canvas=$('cropCanvas'),scale=Math.min(1,1000/Math.max(cropBitmap.width,cropBitmap.height));canvas.width=Math.max(1,Math.round(cropBitmap.width*scale));canvas.height=Math.max(1,Math.round(cropBitmap.height*scale));cropRect=null;cropDraw();}
  function cropPoint(event){const box=$('cropCanvas').getBoundingClientRect();return{x:Math.max(0,Math.min($('cropCanvas').width,(event.clientX-box.left)*$('cropCanvas').width/box.width)),y:Math.max(0,Math.min($('cropCanvas').height,(event.clientY-box.top)*$('cropCanvas').height/box.height))};}
  async function cropOpen(){try{const selected=cover||$('photo').files?.[0];const response=selected?selected:await fetch($('preview').src);if(!selected&&!response.ok)throw Error('Das Cover konnte nicht geladen werden.');const blob=selected||await response.blob();cropBitmap=await createImageBitmap(blob);cropSize();$('cropDialog').showModal();}catch(e){showMessage(e.message||'Bildbearbeitung nicht möglich.',true,true);}}
  function cropClose(){if($('cropDialog').open)$('cropDialog').close();cropBitmap?.close();cropBitmap=null;cropRect=null;cropStart=null;}
  async function cropRotate(){if(!cropBitmap)return;const canvas=document.createElement('canvas');canvas.width=cropBitmap.height;canvas.height=cropBitmap.width;const ctx=canvas.getContext('2d');ctx.translate(canvas.width,0);ctx.rotate(Math.PI/2);ctx.drawImage(cropBitmap,0,0);const rotated=await createImageBitmap(canvas);cropBitmap.close();cropBitmap=rotated;cropSize();}
  async function cropApply(){if(!cropBitmap)return;const display=$('cropCanvas'),r=cropRect||{x:0,y:0,w:display.width,h:display.height};const sx=Math.round(r.x*cropBitmap.width/display.width),sy=Math.round(r.y*cropBitmap.height/display.height),sw=Math.min(cropBitmap.width-sx,Math.round(r.w*cropBitmap.width/display.width)),sh=Math.min(cropBitmap.height-sy,Math.round(r.h*cropBitmap.height/display.height));if(sw<10||sh<10){showMessage('Bitte einen größeren Ausschnitt auswählen.',true,true);return;}const scale=Math.min(1,1600/Math.max(sw,sh));const output=document.createElement('canvas');output.width=Math.max(1,Math.round(sw*scale));output.height=Math.max(1,Math.round(sh*scale));output.getContext('2d').drawImage(cropBitmap,sx,sy,sw,sh,0,0,output.width,output.height);let blob;for(const quality of [.85,.72,.58]){blob=await new Promise(resolve=>output.toBlob(resolve,'image/jpeg',quality));if(blob&&blob.size<=2_000_000)break;}if(!blob||blob.size>2_000_000){showMessage('Das zugeschnittene Bild ist zu groß.',true,true);return;}cover=new File([blob],'cover.jpg',{type:'image/jpeg'});$('photo').value='';const img=$('preview');if(img.dataset.objectUrl)URL.revokeObjectURL(img.dataset.objectUrl);img.src=URL.createObjectURL(cover);img.dataset.objectUrl=img.src;img.hidden=false;$('cameraPrompt').hidden=true;$('removeCover').checked=false;$('scanStatus').textContent='Ausschnitt übernommen. Mit „Änderungen speichern“ wird er für alle sichtbar.';cropClose();}
  function openEditor(set=null){editingSku=set?.sku||null;cover=null;$('form').reset();clearPreview();$('formMessage').hidden=true;$('scanStatus').textContent='';$('editorTitle').textContent=set?'Set bearbeiten':'Set hinzufügen';$('save').textContent=set?'Änderungen speichern':'Für alle speichern';$('sku').readOnly=!!set;$('lookup').hidden=!!set;$('removeCoverLabel').hidden=!set?.imageKey;
    if(set){for(const field of ['sku','name','motifs','topics','location'])$('form').elements.namedItem(field).value=set[field]||'';$('form').elements.namedItem('phrases').value=(set.phrases||[]).join('\n');if(set.imageKey){$('preview').src=set.imageKey;$('preview').hidden=false;$('cameraPrompt').hidden=true;$('cropOpen').hidden=false;}}$('editor').showModal();}
  async function deleteSet(set){if(!confirm('„'+set.name+'“ dauerhaft aus dem gemeinsamen Bestand löschen?'))return;const password=prompt('Admin-Passwort zum Löschen eingeben:');if(password===null)return;if(!password){showMessage('Bitte Admin-Passwort eingeben.',true);return;}
    try{const response=await fetch('/.netlify/functions/sets?sku='+encodeURIComponent(set.sku),{method:'DELETE',headers:{'X-Admin-Password':password},cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error||'Löschen fehlgeschlagen.');await refresh();showMessage('„'+set.name+'“ wurde für alle gelöscht.');}catch(e){showMessage(e.message||'Löschen fehlgeschlagen.',true);}}
  async function save(event){event.preventDefault();if(loading)return;const form=$('form');if(!form.reportValidity())return;loading=true;$('save').disabled=true;$('save').textContent='Speichern …';$('formMessage').hidden=true;try{const selected=$('photo').files?.[0];if(selected&&!cover)cover=await compressImage(selected);const data=new FormData(form);data.delete('password');data.delete('photo');if(cover)data.set('image',cover);if(editingSku){data.set('originalSku',editingSku);if($('removeCover').checked&&!cover)data.set('removeImage','1');}const password=$('password').value;const response=await fetch('/.netlify/functions/sets',{method:editingSku?'PUT':'POST',headers:{'X-Admin-Password':password},body:data,cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error||'Speichern fehlgeschlagen.');const edited=!!editingSku;$('editor').close();form.reset();clearPreview();cover=null;editingSku=null;await refresh();showMessage('„'+result.name+'“ wurde '+(edited?'aktualisiert':'gespeichert')+' und ist jetzt für alle sichtbar.');}catch(e){showMessage(e.message||'Speichern fehlgeschlagen.',true,true);}finally{loading=false;$('save').disabled=false;$('save').textContent=editingSku?'Änderungen speichern':'Für alle speichern';}}
  $('q').addEventListener('input',draw);$('clear').addEventListener('click',()=>{$('q').value='';draw();$('q').focus();});$('add').addEventListener('click',()=>openEditor());$('close').addEventListener('click',()=>$('editor').close());$('cancel').addEventListener('click',()=>$('editor').close());$('editor').addEventListener('click',event=>{if(event.target===$('editor'))$('editor').close();});$('lookup').addEventListener('click',lookup);$('photo').addEventListener('change',event=>{const file=event.target.files?.[0];if(file)readCover(file);});$('form').addEventListener('submit',save);
  $('cropOpen').addEventListener('click',cropOpen);$('cropClose').addEventListener('click',cropClose);$('cropCancel').addEventListener('click',cropClose);$('cropReset').addEventListener('click',()=>{cropRect=null;cropDraw();});$('cropRotate').addEventListener('click',cropRotate);$('cropApply').addEventListener('click',cropApply);$('cropDialog').addEventListener('close',()=>{cropBitmap?.close();cropBitmap=null;});$('cropCanvas').addEventListener('pointerdown',event=>{cropStart=cropPoint(event);$('cropCanvas').setPointerCapture(event.pointerId);cropRect=null;});$('cropCanvas').addEventListener('pointermove',event=>{if(!cropStart)return;const p=cropPoint(event);cropRect={x:Math.min(cropStart.x,p.x),y:Math.min(cropStart.y,p.y),w:Math.abs(p.x-cropStart.x),h:Math.abs(p.y-cropStart.y)};cropDraw();});$('cropCanvas').addEventListener('pointerup',()=>{if(cropRect&&(cropRect.w<5||cropRect.h<5))cropRect=null;cropStart=null;cropDraw();});$('cropCanvas').addEventListener('pointercancel',()=>{cropStart=null;});
  $('imageClose').addEventListener('click',()=>$('imageDialog').close());$('imageDialog').addEventListener('click',event=>{if(event.target===$('imageDialog'))$('imageDialog').close();});$('imageDialog').addEventListener('close',()=>{$('largeImage').removeAttribute('src');});
  refresh();setInterval(refresh,30000);
})();
